name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global init.defaultBranch master

      - name: Setup build environment
        run: ./panda setup

      - name: Build
        run: ./panda jar

      - name: Copy Paperclip jar
        run: |
          cp -v "./paperclip.jar" "./pandaspigot-$GITHUB_RUN_NUMBER.jar"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Server JAR
          path: pandaspigot-${{ github.run_number }}.jar
          archive: false
          if-no-files-found: error
